"""Add image_url to ShopKeep

Revision ID: 47904079d933
Revises: 7e857abd9df8
Create Date: 2025-01-13 22:14:12.413251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47904079d933'
down_revision: Union[str, None] = '7e857abd9df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_table('shopkeep')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopkeep',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('shop_name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('character_class', sa.VARCHAR(), nullable=False),
    sa.Column('voice', sa.VARCHAR(), nullable=False),
    sa.Column('gold', sa.INTEGER(), nullable=False),
    sa.Column('friendship_level', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('damage', sa.VARCHAR(), nullable=True),
    sa.Column('armor_class', sa.INTEGER(), nullable=True),
    sa.Column('shopkeep_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['shopkeep_id'], ['shopkeep.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
