"""Initial setup

Revision ID: 7e857abd9df8
Revises: 
Create Date: 2025-01-08 20:19:08.909904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e857abd9df8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopkeep')
    op.drop_table('item')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('shop_keep_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['shop_keep_id'], ['shopkeep.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopkeep',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('gold', sa.INTEGER(), nullable=False),
    sa.Column('friendship_level', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('shop_name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('character_class', sa.VARCHAR(), nullable=False),
    sa.Column('voice', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
