"""Initial migration

Revision ID: b1e6c3ccdc77
Revises: 
Create Date: 2025-01-26 17:38:31.412815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e6c3ccdc77'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_table('shopkeep')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopkeep',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('shopkeep_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('shop_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('character_class', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('voice', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('personality', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gold', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shop_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('friendship_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='shopkeep_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('damage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('armor_class', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shopkeep_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['shopkeep_id'], ['shopkeep.id'], name='item_shopkeep_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='item_pkey')
    )
    # ### end Alembic commands ###
